[2023-08-24T03:51:35.904+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vnstock-pipeline.Stock_collection_1Y manual__2023-08-23T12:06:15.736835+00:00 [queued]>
[2023-08-24T03:51:35.909+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vnstock-pipeline.Stock_collection_1Y manual__2023-08-23T12:06:15.736835+00:00 [queued]>
[2023-08-24T03:51:35.909+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 5
[2023-08-24T03:51:35.921+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Stock_collection_1Y> on 2023-08-23 12:06:15.736835+00:00
[2023-08-24T03:51:35.925+0000] {standard_task_runner.py:57} INFO - Started process 28654 to run task
[2023-08-24T03:51:35.925+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-08-24T03:51:35.932+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'vnstock-pipeline', 'Stock_collection_1Y', 'manual__2023-08-23T12:06:15.736835+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp8k659coh']
[2023-08-24T03:51:35.932+0000] {standard_task_runner.py:85} INFO - Job 64: Subtask Stock_collection_1Y
[2023-08-24T03:51:35.966+0000] {task_command.py:415} INFO - Running <TaskInstance: vnstock-pipeline.Stock_collection_1Y manual__2023-08-23T12:06:15.736835+00:00 [running]> on host vnstock-pipeline-vm.us-central1-c.c.vnstock-pipeline.internal
[2023-08-24T03:51:35.980+0000] {clientserver.py:505} INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/nguyentuanduong7/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
[2023-08-24T03:51:35.981+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-08-24T03:51:35.981+0000] {java_gateway.py:1052} INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/nguyentuanduong7/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nguyentuanduong7/.local/lib/python3.8/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/nguyentuanduong7/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
[2023-08-24T03:51:35.985+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-08-24T03:51:36.016+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='nguyentuanduong555@gmail.com' AIRFLOW_CTX_DAG_OWNER='Duong' AIRFLOW_CTX_DAG_ID='vnstock-pipeline' AIRFLOW_CTX_TASK_ID='Stock_collection_1Y' AIRFLOW_CTX_EXECUTION_DATE='2023-08-23T12:06:15.736835+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-23T12:06:15.736835+00:00'
[2023-08-24T03:51:36.830+0000] {logging_mixin.py:151} INFO - 1606/1607_SSI
[2023-08-24T03:51:37.525+0000] {logging_mixin.py:151} INFO - 1605/1607_BCM
[2023-08-24T03:51:38.237+0000] {logging_mixin.py:151} INFO - 1604/1607_VHM
[2023-08-24T03:51:38.924+0000] {logging_mixin.py:151} INFO - 1603/1607_VIC
[2023-08-24T03:51:39.617+0000] {logging_mixin.py:151} INFO - 1602/1607_VRE
[2023-08-24T03:51:40.304+0000] {logging_mixin.py:151} INFO - 1601/1607_BVH
[2023-08-24T03:51:41.006+0000] {logging_mixin.py:151} INFO - 1600/1607_POW
[2023-08-24T03:51:41.695+0000] {logging_mixin.py:151} INFO - 1599/1607_GAS
[2023-08-24T03:51:42.390+0000] {logging_mixin.py:151} INFO - 1598/1607_ACB
[2023-08-24T03:51:43.083+0000] {logging_mixin.py:151} INFO - 1597/1607_BID
[2023-08-24T03:51:43.774+0000] {logging_mixin.py:151} INFO - 1596/1607_CTG
[2023-08-24T03:51:44.466+0000] {logging_mixin.py:151} INFO - 1595/1607_HDB
[2023-08-24T03:51:45.157+0000] {logging_mixin.py:151} INFO - 1594/1607_MBB
[2023-08-24T03:51:45.846+0000] {logging_mixin.py:151} INFO - 1593/1607_SSB
[2023-08-24T03:51:46.531+0000] {logging_mixin.py:151} INFO - 1592/1607_SHB
[2023-08-24T03:51:47.214+0000] {logging_mixin.py:151} INFO - 1591/1607_STB
[2023-08-24T03:51:47.909+0000] {logging_mixin.py:151} INFO - 1590/1607_TCB
[2023-08-24T03:51:48.603+0000] {logging_mixin.py:151} INFO - 1589/1607_TPB
[2023-08-24T03:51:49.289+0000] {logging_mixin.py:151} INFO - 1588/1607_VCB
[2023-08-24T03:51:49.982+0000] {logging_mixin.py:151} INFO - 1587/1607_VIB
[2023-08-24T03:51:50.669+0000] {logging_mixin.py:151} INFO - 1586/1607_VPB
[2023-08-24T03:51:51.360+0000] {logging_mixin.py:151} INFO - 1585/1607_HPG
[2023-08-24T03:51:52.052+0000] {logging_mixin.py:151} INFO - 1584/1607_GVR
[2023-08-24T03:51:52.737+0000] {logging_mixin.py:151} INFO - 1583/1607_MSN
[2023-08-24T03:51:53.422+0000] {logging_mixin.py:151} INFO - 1582/1607_VNM
[2023-08-24T03:51:54.114+0000] {logging_mixin.py:151} INFO - 1581/1607_SAB
[2023-08-24T03:51:54.805+0000] {logging_mixin.py:151} INFO - 1580/1607_VJC
[2023-08-24T03:51:55.490+0000] {logging_mixin.py:151} INFO - 1579/1607_MWG
[2023-08-24T03:51:56.187+0000] {logging_mixin.py:151} INFO - 1578/1607_PLX
[2023-08-24T03:51:56.870+0000] {logging_mixin.py:151} INFO - 1577/1607_FPT
[2023-08-24T03:51:57.561+0000] {logging_mixin.py:151} INFO - 1576/1607_MFS
[2023-08-24T03:51:58.244+0000] {logging_mixin.py:151} INFO - 1575/1607_ABC
[2023-08-24T03:51:58.943+0000] {logging_mixin.py:151} INFO - 1574/1607_VGI
[2023-08-24T03:51:59.634+0000] {logging_mixin.py:151} INFO - 1573/1607_FOX
[2023-08-24T03:52:00.330+0000] {logging_mixin.py:151} INFO - 1572/1607_PAI
[2023-08-24T03:52:01.024+0000] {logging_mixin.py:151} INFO - 1571/1607_PIA
[2023-08-24T03:52:01.091+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2023-08-24T03:52:01.094+0000] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 28654. PIDs of all processes in the group: [28654]
[2023-08-24T03:52:01.094+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 28654
[2023-08-24T03:52:01.095+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-08-24T03:52:01.095+0000] {logging_mixin.py:151} INFO - 1570_error_1607_PTP
[2023-08-24T03:52:01.095+0000] {collect_gcs.py:40} ERROR - message
Traceback (most recent call last):
  File "/home/nguyentuanduong7/airflow/src/pluggin/collect_gcs.py", line 29, in stock_collection_1Y
    stock_data=stock_historical_data (symbol=stock, start_date=start_date, end_date=current_date, resolution=resolution, type='stock')
  File "/home/nguyentuanduong7/.local/lib/python3.8/site-packages/vnstock/stock.py", line 148, in stock_historical_data
    df = stock_ohlc(symbol, start_date, end_date, resolution, type, headers)
  File "/home/nguyentuanduong7/.local/lib/python3.8/site-packages/vnstock/stock.py", line 178, in stock_ohlc
    response = requests.request("GET", url, headers=headers).json()
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 535, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 648, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/taskinstance.py", line 1634, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-08-24T03:52:01.799+0000] {logging_mixin.py:151} INFO - 1569/1607_TTN
[2023-08-24T03:52:02.488+0000] {logging_mixin.py:151} INFO - 1568/1607_FUCTVGF3
[2023-08-24T03:52:03.174+0000] {logging_mixin.py:151} INFO - 1567/1607_FUEIP100
[2023-08-24T03:52:03.861+0000] {logging_mixin.py:151} INFO - 1566/1607_FUEKIV30
[2023-08-24T03:52:04.545+0000] {logging_mixin.py:151} INFO - 1565/1607_FUCTVGF4
[2023-08-24T03:52:05.242+0000] {logging_mixin.py:151} INFO - 1564/1607_FUEDCMID
[2023-08-24T03:52:05.928+0000] {logging_mixin.py:151} INFO - 1563/1607_FUEKIVFS
[2023-08-24T03:52:06.613+0000] {logging_mixin.py:151} INFO - 1562/1607_FUEMAVND
[2023-08-24T03:52:07.296+0000] {logging_mixin.py:151} INFO - 1561/1607_FUEFCV50
[2023-08-24T03:52:07.989+0000] {logging_mixin.py:151} INFO - 1560/1607_FUEBFVND
[2023-08-24T03:52:08.678+0000] {logging_mixin.py:151} INFO - 1559/1607_FUESSV50
[2023-08-24T03:52:09.376+0000] {logging_mixin.py:151} INFO - 1558/1607_E1VFVN30
[2023-08-24T03:52:10.066+0000] {logging_mixin.py:151} INFO - 1557/1607_FUESSVFL
[2023-08-24T03:52:10.069+0000] {python.py:194} INFO - Done. Returned value was: Done
[2023-08-24T03:52:10.081+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=vnstock-pipeline, task_id=Stock_collection_1Y, execution_date=20230823T120615, start_date=20230824T035135, end_date=20230824T035210
[2023-08-24T03:52:10.102+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=28654, status='terminated', exitcode=0, started='03:51:35') (28654) terminated with exit code 0
