[2023-08-31T04:05:41.425+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vnstock-pipeline-1H.Successful_Alert_Project_1H scheduled__2023-08-31T03:00:00+00:00 [queued]>
[2023-08-31T04:05:41.430+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vnstock-pipeline-1H.Successful_Alert_Project_1H scheduled__2023-08-31T03:00:00+00:00 [queued]>
[2023-08-31T04:05:41.430+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-08-31T04:05:41.444+0000] {taskinstance.py:1382} INFO - Executing <Task(EmailOperator): Successful_Alert_Project_1H> on 2023-08-31 03:00:00+00:00
[2023-08-31T04:05:41.449+0000] {standard_task_runner.py:57} INFO - Started process 502191 to run task
[2023-08-31T04:05:41.449+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-08-31T04:05:41.456+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'vnstock-pipeline-1H', 'Successful_Alert_Project_1H', 'scheduled__2023-08-31T03:00:00+00:00', '--job-id', '434', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmplctgcmie']
[2023-08-31T04:05:41.456+0000] {standard_task_runner.py:85} INFO - Job 434: Subtask Successful_Alert_Project_1H
[2023-08-31T04:05:41.496+0000] {task_command.py:415} INFO - Running <TaskInstance: vnstock-pipeline-1H.Successful_Alert_Project_1H scheduled__2023-08-31T03:00:00+00:00 [running]> on host vnstock-pipeline-vm.us-central1-c.c.vnstock-pipeline.internal
[2023-08-31T04:05:41.553+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='nguyentuanduong555@gmail.com' AIRFLOW_CTX_DAG_OWNER='Duong_' AIRFLOW_CTX_DAG_ID='vnstock-pipeline-1H' AIRFLOW_CTX_TASK_ID='Successful_Alert_Project_1H' AIRFLOW_CTX_EXECUTION_DATE='2023-08-31T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-31T03:00:00+00:00'
[2023-08-31T04:05:41.560+0000] {logging_mixin.py:151} WARNING - /usr/local/lib/python3.8/dist-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2023-08-31T04:05:41.560+0000] {email.py:270} INFO - Email alerting: attempt 1
[2023-08-31T04:05:41.560+0000] {clientserver.py:505} INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/nguyentuanduong7/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
[2023-08-31T04:05:41.562+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-08-31T04:05:41.562+0000] {java_gateway.py:1052} INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/nguyentuanduong7/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nguyentuanduong7/.local/lib/python3.8/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/nguyentuanduong7/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
[2023-08-31T04:05:41.564+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-08-31T04:05:41.708+0000] {email.py:282} INFO - Sent an alert email to ['nguyentuanduong555@gmail.com']
[2023-08-31T04:05:42.331+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=vnstock-pipeline-1H, task_id=Successful_Alert_Project_1H, execution_date=20230831T030000, start_date=20230831T040541, end_date=20230831T040542
[2023-08-31T04:05:42.349+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-08-31T04:05:42.360+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
